# BoardGameList Agent Configuration
# Agent orchestration system for beautiful architecture maintenance

project:
  name: "BoardGameList"
  version: "1.0.0"
  description: "Smart board game rule book list with agent-driven architecture"
  goal: "Beautiful, scalable architecture for humans, AI, LLM, Serena-MCP, developers, players"

# Core Agent Definitions
agents:
  manager:
    name: "manager_agent"
    role: "Project Coordinator & Orchestrator"
    priority: 1
    status: "active"
    responsibilities:
      - "Project coordination and timeline management"
      - "Task delegation and workflow management" 
      - "Quality assurance across all agents"
      - "Stakeholder communication"
    triggers:
      - "project_milestone_reached"
      - "agent_coordination_needed"
      - "quality_issue_detected"
      - "scope_change_requested"
    calls_other_agents: true
    authority_level: "primary"

  architect:
    name: "architect_agent"
    role: "System Architecture & Technical Design"
    priority: 2
    status: "active"
    responsibilities:
      - "System architecture design and maintenance"
      - "MkDocs configuration and structure"
      - "Technical standards and guidelines"
      - "Scalability planning"
    triggers:
      - "structure_changes_needed"
      - "performance_issues_detected"
      - "scalability_concerns"
      - "technical_standards_updates"
    calls_other_agents: true
    authority_level: "high"

  writer:
    name: "writer_agent"
    role: "Content Creation & Documentation"
    priority: 3
    status: "active"
    responsibilities:
      - "Game documentation creation"
      - "Content quality assurance"
      - "Template development"
      - "Cross-referencing systems"
    triggers:
      - "new_game_documentation_needed"
      - "content_updates_required"
      - "translation_work_needed"
      - "template_updates_required"
    calls_other_agents: true
    authority_level: "medium"

  cleanup:
    name: "cleanup_agent"
    japanese_name: "片付けする人"
    role: "File Organization & Cleanup Specialist"
    priority: 4
    status: "active"
    responsibilities:
      - "Junk file prevention and removal"
      - "File organization and standards"
      - "Content integrity maintenance"
      - "Naming convention enforcement"
    triggers:
      - "junk_files_detected"
      - "file_organization_needed"
      - "post_task_cleanup_required"
      - "scheduled_maintenance"
    calls_other_agents: true
    authority_level: "medium"

  search:
    name: "search_agent"
    japanese_name: "探す人"
    role: "Information Research & Discovery Specialist"
    priority: 5
    status: "active"
    responsibilities:
      - "Board game research and data collection"
      - "Information validation and fact-checking"
      - "Resource discovery"
      - "BGG integration"
    triggers:
      - "research_needed"
      - "information_validation_required"
      - "bgg_data_updates_needed"
      - "fact_checking_requested"
    calls_other_agents: true
    authority_level: "medium"

# Agent Communication Matrix
# Defines which agents call which agents under specific conditions

communication_matrix:
  manager_calls:
    architect:
      triggers:
        - "project_structure_change"
        - "new_requirements"
        - "performance_issues"
      timing: "within_1_hour_of_trigger"
      priority: "high"

    writer:
      triggers:
        - "content_creation_needed"
        - "content_updates_required"
        - "translation_needed"
      timing: "within_30_minutes_of_assignment"
      priority: "high"

    cleanup:
      triggers:
        - "post_task_cleanup"
        - "scheduled_maintenance"
        - "junk_files_detected"
      timing: "within_15_minutes_of_trigger"
      priority: "medium"

    search:
      triggers:
        - "information_gathering_needed"
        - "research_required"
        - "fact_verification_needed"
      timing: "within_20_minutes_of_need"
      priority: "medium"

  architect_calls:
    cleanup:
      triggers:
        - "directory_structure_modified"
        - "architectural_changes_completed"
      timing:
        - "within_5_minutes_of_structure_changes"
        - "immediately_after_major_changes"
      priority: "high"
      requirement: "mandatory"

    writer:
      triggers:
        - "new_content_templates_created"
        - "structural_changes_affect_content"
      timing:
        - "within_30_minutes_of_template_completion"
        - "before_finalizing_architectural_changes"
      priority: "medium"

    manager:
      triggers:
        - "major_architectural_decision_needed"
        - "architecture_milestone_completed"
      timing:
        - "before_implementation_begins"
        - "within_1_hour_of_completion"
      priority: "high"

    search:
      triggers:
        - "technical_research_needed"
      timing: "before_implementation_decisions"
      priority: "low"

  writer_calls:
    search:
      triggers:
        - "new_game_assignment_received"
        - "incomplete_information_discovered"
        - "draft_content_completed"
      timing:
        - "within_10_minutes_of_assignment"
        - "immediately_when_gap_identified"
        - "within_30_minutes_of_draft_completion"
      priority: "high"
      requirement: "mandatory_before_writing"

    cleanup:
      triggers:
        - "multiple_draft_files_created"
        - "game_documentation_completed"
        - "bulk_content_updates"
      timing:
        - "within_15_minutes_of_3+_drafts"
        - "within_5_minutes_of_completion"
        - "within_30_minutes_of_bulk_updates"
      priority: "medium"
      requirement: "mandatory_for_organization"

    architect:
      triggers:
        - "template_limitations_discovered"
        - "new_structural_elements_needed"
      timing:
        - "immediately_when_blocking_writing"
        - "within_20_minutes_of_discovery"
      priority: "medium"

    manager:
      triggers:
        - "content_scope_exceeds_assignment"
        - "assigned_content_completed"
        - "quality_issues_affect_multiple_games"
      timing:
        - "within_1_hour_of_scope_identification"
        - "within_30_minutes_of_completion"
        - "immediately_when_pattern_identified"
      priority: "high"

  cleanup_calls:
    architect:
      triggers:
        - "structural_inconsistencies_discovered"
        - "major_directory_reorganization_completed"
      timing:
        - "immediately_when_problem_identified"
        - "within_15_minutes_of_reorganization"
      priority: "high"
      requirement: "pause_cleanup_for_guidance"

    writer:
      triggers:
        - "content_reorganization_needed"
        - "duplicate_content_discovered"
      timing:
        - "within_10_minutes_of_discovery"
        - "immediately_when_duplicates_found"
      priority: "medium"
      requirement: "halt_cleanup_of_affected_files"

    manager:
      triggers:
        - "systemic_project_issues_discovered"
        - "major_cleanup_completed"
        - "cleanup_blocked_by_dependencies"
      timing:
        - "within_30_minutes_of_discovery"
        - "within_15_minutes_of_completion"
        - "immediately_when_blocked"
      priority: "high"

    search:
      triggers:
        - "orphaned_files_need_verification"
      timing: "within_5_minutes_of_discovery"
      priority: "low"

  search_calls:
    writer:
      triggers:
        - "research_request_completed"
        - "content_gaps_discovered"
        - "conflicting_information_found"
      timing:
        - "within_30_minutes_of_completion"
        - "within_1_hour_of_discovery"
        - "immediately_when_conflict_identified"
      priority: "high"
      requirement: "mandatory_result_delivery"

    manager:
      triggers:
        - "research_scope_exceeds_estimate"
        - "high_priority_research_completed"
        - "required_information_unavailable"
      timing:
        - "within_2_hours_of_scope_expansion"
        - "within_15_minutes_of_completion"
        - "after_4_hours_or_sources_exhausted"
      priority: "high"

    cleanup:
      triggers:
        - "multiple_research_files_created"
        - "major_research_project_completed"
      timing:
        - "within_20_minutes_of_accumulation"
        - "within_30_minutes_of_completion"
      priority: "low"

    architect:
      triggers:
        - "architectural_information_needs_identified"
      timing: "within_1_hour_of_identification"
      priority: "low"

# Workflow Definitions
workflows:
  new_game_addition:
    description: "Complete workflow for adding new board game documentation"
    sequence:
      1:
        agent: "manager"
        action: "receives_new_game_request"
        calls: "search"
        timing: "immediate"
        system_prompt: "Search Agent: Collect comprehensive data for [GAME_NAME] including BGG ratings, official rules, component lists."

      2:
        agent: "search"
        action: "completes_research"
        calls: "writer"
        timing: "within_30_minutes"
        system_prompt: "Writer Agent: Research completed for [GAME_NAME]. Data package ready for content creation."

      3:
        agent: "writer"
        action: "creates_documentation"
        calls: "cleanup"
        timing: "within_5_minutes_of_completion"
        system_prompt: "Cleanup Agent: Documentation for [GAME_NAME] completed. Clean up all draft files and organize final content."

      4:
        agent: "cleanup"
        action: "organizes_content"
        calls: "manager"
        timing: "within_15_minutes"
        system_prompt: "Manager Agent: [GAME_NAME] documentation completed and organized. Ready for review."

  weekly_maintenance:
    description: "Scheduled maintenance workflow"
    schedule: "weekly"
    sequence:
      1:
        agent: "manager"
        action: "initiates_maintenance"
        calls: "cleanup"
        timing: "maintenance_window"

      2:
        agent: "cleanup"
        action: "comprehensive_cleanup"
        calls: "architect"
        timing: "after_cleanup"

      3:
        agent: "architect"
        action: "structure_validation"
        calls: "manager"
        timing: "within_30_minutes"

# Quality Standards
quality_standards:
  file_organization:
    junk_files: "zero_tolerance"
    naming_conventions: "100%_compliance"
    directory_structure: "standardized"

  content_quality:
    accuracy: "95%_minimum"
    completeness: "all_sections_required"
    consistency: "template_adherence"

  performance:
    response_times:
      cleanup: "within_15_minutes"
      research: "within_4_hours"
      content_creation: "within_1_week"
    
  architecture:
    scalability: "supports_100+_games"
    maintainability: "clean_code_standards"
    documentation: "comprehensive_coverage"

# Emergency Protocols
emergency_protocols:
  critical_issues:
    build_failure:
      first_responder: "architect"
      escalation_time: "15_minutes"
      escalate_to: "manager"

    content_corruption:
      first_responder: "cleanup"
      escalation_time: "10_minutes"
      escalate_to: "manager"

    research_unavailable:
      first_responder: "search"
      escalation_time: "4_hours"
      escalate_to: "manager"

# Success Metrics
metrics:
  project_health:
    games_documented: "target_6_core_games"
    file_organization_score: "95%_minimum"
    build_performance: "under_2_seconds"
    agent_coordination: "successful_handoffs_90%+"

  agent_performance:
    response_times: "within_defined_limits"
    task_completion: "95%_success_rate"
    communication_efficiency: "clear_handoffs"
    quality_delivery: "meets_all_standards"

# Project Phases
phases:
  foundation:
    description: "Initial 6 games and core infrastructure"
    primary_agents: ["manager", "architect", "writer", "search"]
    success_criteria: "6_games_documented_with_beautiful_architecture"

  expansion:
    description: "Additional games and enhanced features"
    primary_agents: ["all_agents"]
    success_criteria: "25+_games_with_maintained_quality"

  community:
    description: "Community contributions and advanced features"
    primary_agents: ["all_agents_plus_specialized"]
    success_criteria: "100+_games_with_community_engagement"